name: Linting, testing, and building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent --ignore-scripts
      - name: Build project in production mode
        run: yarn build:prod
      - name: Linting typescript
        run: yarn lint:ts
      - name: Linting scss
        run: yarn lint:scss
      - name: Unit tests
        run: yarn test:unit
      - name: Build storybook
        run: yarn storybook:build
      - name: Screenshot tests
        run: yarn test:ui:ci
        
